[build]
  publish = "."  # Publish everything in the current directory
  
[build.environment]
  NODE_VERSION = "16"

# Set headers for all files
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
# Configure CORS specifically for images
[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect all routes to index.html to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200